CREATE DATABASE IF NOT EXISTS bolsiyo;

USE bolsiyo;

CREATE TABLE IF NOT EXISTS companies(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  address VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  isActive BOOLEAN NOT NULL
);

CREATE TABLE products(
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  brand VARCHAR(100) NOT NULL,
  categoryId INT(11) NOT NULL,
  quantity INT(11) NOT NULL,
  price INT(11) NOT NULL,
  companyId INT(11) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP,
  deletedAt TIMESTAMP,
  CONSTRAINT FK_CATEGORY
    FOREIGN KEY (categoryId) REFERENCES categories(id),
  CONSTRAINT FK_COMPANY
    FOREIGN KEY (companyId) REFERENCES companies(id)
);

DESCRIBE products;